package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

// Roleid is the resolver for the roleid field.
// func (r *userResolver) Roleid(ctx context.Context, obj *entity.User) (int, error) {
// 	panic(fmt.Errorf("not implemented: Roleid - roleid"))
// }

// User returns UserResolver implementation.
// func (r *Resolver) User() UserResolver { return &userResolver{r} }

// type userResolver struct{ *Resolver }
