package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

// Goalnya nanti adalah membuat sebuah domain layer yang digunakan untuk fetching dari resovler schema
