package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/adiatma85/exp-golang-graphql/graph/model"
	"github.com/adiatma85/exp-golang-graphql/src/business/entity"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.Login) (string, error) {
	userLoginReq := entity.UserLoginRequest{
		Email:    input.Email,
		Password: input.Password,
	}
	userJwt, err := r.Uc.User.SignInWithPassword(ctx, userLoginReq)
	if err != nil {
		return "", err
	}

	return userJwt.AccessToken, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
